name: Bug Report
description: Report a bug for this project.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: title
    attributes:
      label: "Bug Title"
      description: "What is the title of the bug?"
      placeholder: "Enter title here"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "Please describe the bug in detail."
      placeholder: "Enter description here"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide the steps to reproduce the bug."
      placeholder: "Enter steps here"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What is the expected behavior?"
      placeholder: "Enter expected behavior here"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What is the actual behavior?"
      placeholder: "Enter actual behavior here"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Version"
      description: "What version of the project are you using?"
      placeholder: "Enter version here"
    validations:
      required: true
