name: "🐞 Bug"
description: File a bug/issue
title: "[BUG] This a bug"
labels: ["Bug", "Needs Triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Anything else?
        * Links? References? Anything that will give us more context about the issue you are encountering!
        * Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
 - type: textarea
    attributes:
      label: Name
